/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'ActiveTournamentWithLeaderboard': { kind: 'OBJECT'; name: 'ActiveTournamentWithLeaderboard'; fields: { 'endDate': { name: 'endDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'leaderboard': { name: 'leaderboard'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LeaderboardEntry'; ofType: null; }; }; }; } }; 'matches': { name: 'matches'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Match'; ofType: null; }; }; }; } }; 'startDate': { name: 'startDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'winnerId': { name: 'winnerId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'Boolean': unknown;
    'DateTime': unknown;
    'EloDataPoint': { kind: 'OBJECT'; name: 'EloDataPoint'; fields: { 'elo': { name: 'elo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'timestamp': { name: 'timestamp'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Float': unknown;
    'Group': { kind: 'OBJECT'; name: 'Group'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'players': { name: 'players'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; }; }; } }; }; };
    'ID': unknown;
    'Int': unknown;
    'LeaderboardEntry': { kind: 'OBJECT'; name: 'LeaderboardEntry'; fields: { 'allTimeElo': { name: 'allTimeElo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'allTimeEloRating': { name: 'allTimeEloRating'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'avatarFilename': { name: 'avatarFilename'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'playerId': { name: 'playerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'playerName': { name: 'playerName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Match': { kind: 'OBJECT'; name: 'Match'; fields: { 'completed': { name: 'completed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'numOfRounds': { name: 'numOfRounds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'playerResults': { name: 'playerResults'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerMatchResult'; ofType: null; }; }; }; } }; 'rounds': { name: 'rounds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Round'; ofType: null; }; }; }; } }; 'teams': { name: 'teams'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Team'; ofType: null; }; }; }; } }; 'time': { name: 'time'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'tournamentId': { name: 'tournamentId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'cancelMatch': { name: 'cancelMatch'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'completeTournament': { name: 'completeTournament'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Tournament'; ofType: null; }; } }; 'createGroup': { name: 'createGroup'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'createMatchWithRounds': { name: 'createMatchWithRounds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Match'; ofType: null; }; } }; 'createPlayer': { name: 'createPlayer'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; } }; 'createTournament': { name: 'createTournament'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Tournament'; ofType: null; }; } }; 'recordRoundResults': { name: 'recordRoundResults'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Match'; ofType: null; }; } }; 'swapRoundPlayer': { name: 'swapRoundPlayer'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Match'; ofType: null; }; } }; }; };
    'Player': { kind: 'OBJECT'; name: 'Player'; fields: { 'avatarFilename': { name: 'avatarFilename'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'currentTournamentElo': { name: 'currentTournamentElo'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'eloRating': { name: 'eloRating'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'matchHistory': { name: 'matchHistory'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerMatchHistoryEntry'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'trackStats': { name: 'trackStats'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerTrackStats'; ofType: null; }; }; }; } }; }; };
    'PlayerEloHistory': { kind: 'OBJECT'; name: 'PlayerEloHistory'; fields: { 'dataPoints': { name: 'dataPoints'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'EloDataPoint'; ofType: null; }; }; }; } }; 'playerId': { name: 'playerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'playerName': { name: 'playerName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'PlayerMatchHistoryEntry': { kind: 'OBJECT'; name: 'PlayerMatchHistoryEntry'; fields: { 'eloChange': { name: 'eloChange'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'matchId': { name: 'matchId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'matchTime': { name: 'matchTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'tournamentEloChange': { name: 'tournamentEloChange'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'PlayerTrackStats': { kind: 'OBJECT'; name: 'PlayerTrackStats'; fields: { 'averagePosition': { name: 'averagePosition'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'racesPlayed': { name: 'racesPlayed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'trackName': { name: 'trackName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'PlayerMatchResult': { kind: 'OBJECT'; name: 'PlayerMatchResult'; fields: { 'eloChange': { name: 'eloChange'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'player': { name: 'player'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'teammateContribution': { name: 'teammateContribution'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'tournamentEloChange': { name: 'tournamentEloChange'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'tournamentEloFromContributions': { name: 'tournamentEloFromContributions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'tournamentEloFromRaces': { name: 'tournamentEloFromRaces'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'PlayerRaceResult': { kind: 'OBJECT'; name: 'PlayerRaceResult'; fields: { 'player': { name: 'player'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'tournamentEloChange': { name: 'tournamentEloChange'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'PlayerResultInput': { kind: 'INPUT_OBJECT'; name: 'PlayerResultInput'; isOneOf: false; inputFields: [{ name: 'playerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }]; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'activeTournament': { name: 'activeTournament'; type: { kind: 'OBJECT'; name: 'ActiveTournamentWithLeaderboard'; ofType: null; } }; 'currentGroup': { name: 'currentGroup'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Group'; ofType: null; }; } }; 'login': { name: 'login'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'matchById': { name: 'matchById'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Match'; ofType: null; }; } }; 'playerById': { name: 'playerById'; type: { kind: 'OBJECT'; name: 'Player'; ofType: null; } }; 'players': { name: 'players'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; }; }; } }; 'tournamentById': { name: 'tournamentById'; type: { kind: 'OBJECT'; name: 'TournamentDetail'; ofType: null; } }; 'tournaments': { name: 'tournaments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TournamentSummary'; ofType: null; }; }; }; } }; 'tracks': { name: 'tracks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Track'; ofType: null; }; }; }; } }; }; };
    'RaceResultUpdate': { kind: 'OBJECT'; name: 'RaceResultUpdate'; fields: { 'leaderboard': { name: 'leaderboard'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LeaderboardEntry'; ofType: null; }; }; }; } }; 'matchCompleted': { name: 'matchCompleted'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'matchId': { name: 'matchId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'playerAggregates': { name: 'playerAggregates'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerMatchResult'; ofType: null; }; }; }; } }; 'raceResults': { name: 'raceResults'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerRaceResult'; ofType: null; }; }; }; } }; 'roundCompleted': { name: 'roundCompleted'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'roundNumber': { name: 'roundNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'teams': { name: 'teams'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Team'; ofType: null; }; }; }; } }; 'tournamentId': { name: 'tournamentId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'Round': { kind: 'OBJECT'; name: 'Round'; fields: { 'completed': { name: 'completed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'players': { name: 'players'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RoundPlayer'; ofType: null; }; }; }; } }; 'results': { name: 'results'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerRaceResult'; ofType: null; }; }; }; } }; 'roundNumber': { name: 'roundNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'track': { name: 'track'; type: { kind: 'OBJECT'; name: 'Track'; ofType: null; } }; }; };
    'RoundPlayer': { kind: 'OBJECT'; name: 'RoundPlayer'; fields: { 'avatarFilename': { name: 'avatarFilename'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'teamId': { name: 'teamId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'String': unknown;
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'raceResultsUpdated': { name: 'raceResultsUpdated'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RaceResultUpdate'; ofType: null; }; } }; }; };
    'Team': { kind: 'OBJECT'; name: 'Team'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'players': { name: 'players'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Player'; ofType: null; }; }; }; } }; 'score': { name: 'score'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'teamNum': { name: 'teamNum'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Tournament': { kind: 'OBJECT'; name: 'Tournament'; fields: { 'endDate': { name: 'endDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'leaderboard': { name: 'leaderboard'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LeaderboardEntry'; ofType: null; }; }; }; } }; 'matches': { name: 'matches'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Match'; ofType: null; }; }; }; } }; 'startDate': { name: 'startDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'stats': { name: 'stats'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TournamentStat'; ofType: null; }; }; }; } }; 'winnerId': { name: 'winnerId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'TournamentDetail': { kind: 'OBJECT'; name: 'TournamentDetail'; fields: { 'endDate': { name: 'endDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'leaderboard': { name: 'leaderboard'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LeaderboardEntry'; ofType: null; }; }; }; } }; 'playerEloHistory': { name: 'playerEloHistory'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlayerEloHistory'; ofType: null; }; }; }; } }; 'startDate': { name: 'startDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'stats': { name: 'stats'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TournamentStat'; ofType: null; }; }; }; } }; 'winnerId': { name: 'winnerId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'TournamentStat': { kind: 'OBJECT'; name: 'TournamentStat'; fields: { 'extraData': { name: 'extraData'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'playerId': { name: 'playerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'statType': { name: 'statType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'TournamentStatType'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'TournamentStatType': { name: 'TournamentStatType'; enumValues: 'BEST_TEAMMATE' | 'WORST_TEAMMATE' | 'BEST_RACE' | 'WORST_RACE' | 'BIGGEST_SWING' | 'MOST_HELPED' | 'MOST_HURT' | 'BEST_MATCH' | 'WORST_MATCH'; };
    'TournamentSummary': { kind: 'OBJECT'; name: 'TournamentSummary'; fields: { 'endDate': { name: 'endDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'startDate': { name: 'startDate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'winnerId': { name: 'winnerId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'Track': { kind: 'OBJECT'; name: 'Track'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: 'Subscription';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}