/* eslint-disable */
/* prettier-ignore */

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This will be generated by running `pnpm graphql:generate`
 * It is based on your schema at http://localhost:8080/graphql
 */
export type introspection = {
  __schema: {
    queryType: {
      name: 'Query'
    }
    mutationType: {
      name: 'Mutation'
    }
    subscriptionType: null
    types: []
  }
}
